Repository OZ-Coding-School/oz_externship_fe_02_team4, pull requests merged in 2025-09, with the labels that each got.

#38 Fix: 디스코드 웹훅 yml 파일 오타 수정
  .github/workflows/discord-notifications.yml
Labels: 🐛 Bug

#40 Feature: 공통 입력 필드 컴포넌트
  src/components/common/input/Input.tsx
Labels: ✨ Feature

#51 Fix: 공용 입력 필드 컴포넌트 버그 수정
  src/components/common/Input.tsx
Labels: 🐛 Bug

#56 Feature: 공용 드롭다운 컴포넌트
  src/components/common/Dropdown.tsx
  src/index.css
Labels: ✨ Feature

#54 Feature: landing page
  src/App.tsx
  src/assets/images/LandingPageImage.jpg
  src/assets/images/StudyGroupIcon.png
  src/components/common/Card/BenefitCard.tsx
  src/components/index.tsx
  src/pages/LandingPage.tsx
  src/pages/index.tsx
Labels: ✨ Feature

#66 Feature/header 컴포넌트 분리 / 모바일 UI 추가.
  src/App.tsx
  src/components/common/Logo.tsx
  src/components/common/Symbol.tsx
  src/components/header.tsx
  src/components/header/Header.tsx
  src/components/header/HeaderLogo.tsx
  src/components/header/HeaderMobile.tsx
  src/components/header/NavComponent.tsx
  src/components/header/NavList.tsx
  src/components/index.tsx
Labels: ✨ Feature, ♻️ Refactor

#73 Chore: 리액트 라우터 돔 설치
  package-lock.json
  package.json
Labels: ⚙ Setting

#79 Feature: 공통 스켈레톤 UI 추가
  src/components/common/Skeleton/AvatarSkeleton.tsx
  src/components/common/Skeleton/ImageCardSkeleton.tsx
  src/components/common/Skeleton/ListItemSkeleton.tsx
  src/components/common/Skeleton/SkeletonItem.tsx
  src/components/index.tsx
  src/index.css
Labels: ✨ Feature

#86 Feature: 조건부 렌더링용 화면 상태 UI 추가
  src/components/common/State/BaseState.tsx
  src/components/common/State/EmptyDataState.tsx
  src/components/common/State/EmptyResultState.tsx
  src/components/common/State/LoadingState.tsx
  src/index.css
Labels: ✨ Feature

#85 Feature: 공용 아바타 컴포넌트 생성
  src/components/avatar/Avatar.tsx
  src/components/avatar/AvatarSize.ts
  src/components/common/Skeleton/AvatarSkeleton.tsx
  src/components/index.tsx
Labels: ✨ Feature

#92 Feature: 알림 UI
  src/components/index.tsx
  src/components/notification/Notification.tsx
  src/components/notification/NotificationCard.tsx
  src/components/notification/NotificationIcon.tsx
  src/components/notification/NotificationNavigation.tsx
  src/store/index.ts
  src/store/useNotificationNavigationItemStore.tsx
  src/types/api-response-types/notification-response-types.ts
Labels: ✨ Feature

#94 Feature: 마이페이지 내 정보 페이지
  src/App.tsx
  src/components/index.tsx
  src/components/layout/MyPageLayout.tsx
  src/components/mypage/InfoDescription.tsx
  src/pages/MyInfo.tsx
  src/pages/index.tsx
Labels: ✨ Feature

#99 Setting: msw 세팅
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
Labels: ⚙ Setting

#103 Feature: 테스트 허브 추가
  src/App.tsx
  src/pages/TestHub.tsx
  src/routes/MainRoutes.tsx
  src/routes/TestRoutes.tsx
  src/tests/InputTest.tsx
  src/tests/ToastTest.tsx
  src/utils/index.ts
  src/utils/registryTestPages.ts
Labels: ✨ Feature

#104 Feature:93-avatarRefactoring
  src/components/avatar/Avatar.tsx
  src/components/common/Skeleton/AvatarSkeleton.tsx
  src/components/index.tsx
  src/components/mypage/MyPageSideBar.tsx
  src/components/mypage/MyPageSideBarMenu.tsx
  src/components/mypage/MyPageSideBarProfile.tsx
  src/constants/avatar-size.ts
  src/pages/MyInfo.tsx
Labels: ♻️ Refactor

#106 Fix: react-router 라이브러리 통일
  package-lock.json
  package.json
Labels: 🐛 Bug

#116 Refactor: Input 컴포넌트 리팩토링
  src/components/chat/ChatRoomInput.tsx
  src/components/common/Input.tsx
  src/components/common/input/Input.tsx
  src/components/common/input/InputDescription.tsx
  src/components/common/input/InputErrorMessage.tsx
  src/components/common/input/InputIcon.tsx
  src/components/common/input/InputLabel.tsx
  src/components/common/input/index.ts
  src/components/index.tsx
  src/tests/InputTest.tsx
Labels: ✨ Feature

#124 Feature:110-mypagemodals 내정보 수정/ 비밀번호 변경/ 회원탈퇴 모달 UI 생성
  src/components/common/Avatar.tsx
  src/components/common/Button.tsx
  src/components/index.tsx
  src/components/mypage/myinfo/InfoDescription.tsx
  src/components/mypage/myinfo/InfoUpdate.tsx
  src/components/mypage/myinfo/MypageInputField.tsx
  src/components/mypage/myinfo/PasswordChange.tsx
  src/components/mypage/myinfo/Withdrawal.tsx
  src/components/mypage/sidebar/MyPageSideBar.tsx
  src/components/mypage/sidebar/MyPageSideBarMenu.tsx
  src/components/mypage/sidebar/MyPageSideBarProfile.tsx
  src/constants/avatar-size.ts
  src/constants/button-variants.ts
  src/pages/MyInfo.tsx
Labels: ✨ Feature, ♻️ Refactor

#127 Refactor: 컴포넌트 경로 정리.
  src/components/index.tsx
  src/components/layout/MyPageLayout.tsx
  src/components/my-page/BookmarkedRecruitmentCard.tsx
  src/components/my-page/index.tsx
  src/components/my-page/my-info/InfoDescription.tsx
  src/components/my-page/my-info/InfoUpdate.tsx
  src/components/my-page/my-info/MypageInputField.tsx
  src/components/my-page/my-info/PasswordChange.tsx
  src/components/my-page/my-info/Withdrawal.tsx
  src/components/my-page/side-bar/MyPageSideBar.tsx
  src/components/my-page/side-bar/MyPageSideBarMenu.tsx
  src/components/my-page/side-bar/MyPageSideBarProfile.tsx
  src/pages/index.tsx
  src/pages/my-page/BookmarkedRecruitment.tsx
  src/pages/my-page/MyInfo.tsx
Labels: ♻️ Refactor

#134 Feature: Auth 폼 유효성 검사 기능 및 테스트 페이지 추가
  src/schemas/form-schema/auth-schema.ts
  src/tests/AuthFormVerificationTest.tsx
Labels: ✨ Feature

#137 Bug: 공용 드롭다운 컴포넌트 에러 해결 및 수정
  src/components/common/Dropdown.tsx
  src/components/index.tsx
Labels: 🐛 Bug

#171 Feature:154 지원 상세정보 모달 api 연동로직 구현 / mockdata 연결
  src/components/my-page/applied-recruitment/ApplicantDetail.tsx
  src/components/my-page/applied-recruitment/ApplicationDetailModal.tsx
  src/components/my-page/applied-recruitment/AppliedStatusBadge.tsx
  src/components/my-page/index.tsx
  src/components/my-page/side-bar/MyPageSideBar.tsx
  src/hooks/api/useApplicationDetail.tsx
  src/hooks/api/useAppliedRecruitment.tsx
  src/mocks/data/applications.ts
  src/mocks/data/applied-recruitments-data.ts
  src/mocks/handlers.ts
  src/mocks/handlers/applied-recruitments-handler.ts
  src/mocks/handlers/applied-recruitments.ts
  src/pages/my-page/AppliedRecruitment.tsx
  src/routes/MainRoutes.tsx
  src/types/api-response-types/recruitment-response-types.ts
  src/utils/formatted-dates.ts
Labels: ✨ Feature, ♻️ Refactor

#172 Feature: 알림 목서버
  src/components/notification/Notification.tsx
  src/components/notification/NotificationCard.tsx
  src/hooks/api/useNotification.ts
  src/mocks/data/notification.ts
  src/mocks/handlers.ts
  src/mocks/handlers/notification.ts
  src/tests/NotificationTest.tsx
  src/types/api-response-types/notification-response-types.ts
Labels: ✨ Feature

#175 Rename: Mocks 디렉토리 파일명 수정
  src/mocks/data/applications-data.ts
  src/mocks/data/bookmarked-lectures-data.ts
  src/mocks/data/bookmarked-recruitments-data.ts
  src/mocks/data/chat-room-data.ts
  src/mocks/data/notification-data.ts
  src/mocks/data/user-information-data.ts
  src/mocks/handlers.ts
  src/mocks/handlers/applied-recruitments-handler.ts
  src/mocks/handlers/bookmarked-lectures-handler.ts
  src/mocks/handlers/bookmarked-recruitments-handler.ts
  src/mocks/handlers/chat-handler.ts
  src/mocks/handlers/notification-handler.ts
  src/mocks/handlers/user-information-handler.ts
Labels: 🚚 Rename

#184 Fix: 사용하지 않은 테스트 페이지 삭제
  src/tests/ApplicantDetailTest.tsx
Labels: 🐛 Bug

#182 Feature: 이메일 찾기 & 비밀번호 찾기 공용 컴포넌트 추가
  src/components/auth/AuthIcon.tsx
  src/components/auth/AuthStep.tsx
  src/hooks/index.ts
  src/hooks/useTimer.tsx
  src/hooks/useVerificationCode.tsx
  src/pages/SignUp.tsx
  src/pages/TestHub.tsx
  src/schemas/form-schema/find-email-schema.ts
  src/tests/StepTest.tsx
Labels: ✨ Feature

#186 ♻️ Refactor: 지원내역 목록/ 지원상세 정보 관련 이슈사항 리팩토링 (#181)
  src/components/my-page/applied-recruitment/ApplicationDetailModal.tsx
  src/hooks/api/index.ts
  src/hooks/api/useApplicationDetail.ts
  src/mocks/handlers/applied-recruitments-handler.ts
  src/pages/my-page/AppliedRecruitment.tsx
Labels: ♻️ Refactor

#188 Feature: 로그인 & 로그아웃 msw 적용
  src/components/auth/AuthSocialLoginButton.tsx
  src/hooks/api/auth/useLogin.ts
  src/hooks/api/auth/useLogout.ts
  src/hooks/api/auth/useUserInformation.ts
  src/hooks/api/index.ts
  src/mocks/data/user-login-data.ts
  src/mocks/handlers.ts
  src/mocks/handlers/auth-handler.ts
  src/mocks/handlers/user-information-handler.ts
  src/pages/Login.tsx
  src/tests/LoginTest.tsx
  src/tests/UserInformationTest.tsx
  src/types/api-request-types/auth-request-types.ts
  src/types/api-response-types/auth-response-types.ts
  src/utils/axios.ts
  src/utils/formatted-dates.ts
Labels: ✨ Feature

#202 Refactor: 인증 & 인가 처리 방식 변경
  src/App.tsx
  src/constants/api-endpoints.ts
  src/hooks/api/auth/useLogin.ts
  src/hooks/api/auth/useLogout.ts
  src/hooks/api/auth/useTokenRefresh.ts
  src/hooks/api/auth/useUserInformation.ts
  src/hooks/api/useAxiosInterceptor.ts
  src/hooks/useToast.ts
  src/hooks/useVerificationCode.ts
  src/mocks/handlers/auth-handler.ts
  src/pages/LandingPage.tsx
  src/pages/TestHub.tsx
  src/store/useLoginStore.ts
  src/tests/LoginTest.tsx
  src/utils/axios.ts
  src/utils/check-endpoints.ts
  src/utils/index.ts
  src/utils/manage-token.ts
Labels: ♻️ Refactor

#203 Fix: 북마크한 강의 타입 변경
  src/hooks/api/bookmarked/useBookmarkedLecture.ts
  src/hooks/api/bookmarked/useInfiniteBookmarkedLecture.ts
  src/mocks/data/bookmarked-lectures-data.ts
  src/types/api-request-types/bookmarked-request-types.ts
  src/types/api-response-types/lecture-response-type.ts
  src/types/index.ts
Labels: 🐛 Bug

#204 Feature:187 리뷰 작성모달 UI 생성
  src/components/my-page/completed-study/CompletedStudyImageCard.tsx
  src/components/my-page/completed-study/RatingStarInput.tsx
  src/components/my-page/completed-study/ReviewInputModal.tsx
  src/components/my-page/index.tsx
  src/mocks/data/completed-study-data.ts
Labels: ✨ Feature

#233 Setting: msw 설정 변경
  src/constants/url-constants.ts
  src/hooks/api/auth/useLogin.ts
  src/hooks/api/auth/useLogout.ts
  src/hooks/api/auth/useTokenRefresh.ts
  src/hooks/api/auth/useUserInformation.ts
  src/hooks/api/auth/useUserRecover.ts
  src/hooks/api/auth/useUserRecoverEmailSend.ts
  src/hooks/api/bookmarked/useBookmarkedLecture.ts
  src/hooks/api/bookmarked/useBookmarkedRecruitments.ts
  src/hooks/api/bookmarked/useInfiniteBookmarkedLecture.ts
  src/hooks/api/bookmarked/useInfiniteBookmarkedRecruitment.ts
  src/hooks/api/chat/useChatMessages.ts
  src/hooks/api/useApplicationDetail.ts
  src/hooks/api/useAppliedRecruitment.ts
  src/hooks/api/useCompletedStudy.ts
  src/hooks/api/useNotification.ts
  src/main.tsx
  src/mocks/handlers.ts
  src/mocks/handlers/applied-recruitments-handler.ts
  src/mocks/handlers/auth-handler.ts
  src/mocks/handlers/bookmarked-lectures-handler.ts
  src/mocks/handlers/bookmarked-recruitments-handler.ts
  src/mocks/handlers/chat-handler.ts
  src/mocks/handlers/completed-study-handler.ts
  src/mocks/handlers/notification-handler.ts
  src/mocks/handlers/user-recover-handler.ts
  src/utils/axios.ts
Labels: ⚙ Setting

#237 Feature: 북마크 기능
  src/components/my-page/bookmarked-lecture/BookmarkedLectureCard.tsx
  src/components/my-page/bookmarked-lecture/LectureBookmarkIcon.tsx
  src/components/my-page/bookmarked-recruitment/BookmarkedRecruitmentCard.tsx
  src/components/my-page/bookmarked-recruitment/RecruitmentBookmarkIcon.tsx
  src/components/my-page/index.tsx
  src/hooks/api/bookmarked/useToggleLectureBookmark.ts
  src/hooks/api/bookmarked/useToggleRecruitmentBookmark.ts
  src/hooks/api/index.ts
  src/mocks/handlers/bookmarked-lectures-handler.ts
  src/mocks/handlers/bookmarked-recruitments-handler.ts
  src/tests/BookmarkTest.tsx
Labels: ✨ Feature

#242 refactor: useVerificationCode에 탈퇴 회원 복구 로직 추가
  src/components/auth/user-recover-modal/UserRecoverFormModal.tsx
  src/hooks/api/auth/useUserRecover.ts
  src/hooks/api/auth/useUserRecoverEmailSend.ts
  src/hooks/api/auth/useUserRecoverSendCode.ts
  src/hooks/api/auth/useUserRecoverVerify.ts
  src/hooks/api/index.ts
  src/hooks/useVerificationCode.ts
  src/types/api-request-types/user-recover-request-types.ts
Labels: ♻️ Refactor

#244 Setting: 등록하지 않은 핸들러 bypass 하도록 설정
  src/main.tsx
Labels: ⚙ Setting

#247 Refactor: 로그인 관련 msw 수정 및 api 적용
  src/components/auth/user-recover-modal/UserRecoverNoticeModal.tsx
  src/hooks/api/auth/useLogin.ts
  src/hooks/api/auth/useLogout.ts
  src/hooks/api/auth/useTokenRefresh.ts
  src/mocks/handlers/auth-handler.ts
  src/pages/auth/Login.tsx
  src/store/index.ts
  src/store/useWithdrawalDateStore.ts
  src/types/api-response-types/auth-response-types.ts
  src/utils/formatted-dates.ts
  src/utils/manage-token.ts
Labels: ♻️ Refactor

#254 Refactor: React Query 에러 처리 로직 수정
  src/hooks/api/auth/useEmailSendCode.ts
  src/hooks/api/auth/useEmailVerify.ts
  src/hooks/api/auth/useLogin.ts
  src/hooks/api/auth/usePhoneSendCode.ts
  src/hooks/api/auth/usePhoneVerify.ts
  src/hooks/api/auth/useSignup.ts
  src/pages/auth/Login.tsx
Labels: ♻️ Refactor

#258 Fix: 가입하지 않은 사용자 로그인 시도 버그 수정
  src/hooks/api/auth/useLogin.ts
  src/pages/auth/Login.tsx
Labels: 🐛 Bug

#261 Design: 토스트 메시지 반응형 UI 추가
  src/components/common/toast/ToastContainer.tsx
  src/components/common/toast/ToastItem.tsx
Labels: 💄 Design

#260 Feature:229 내 정보 수정/ 비밀번호 변경 api 로직 구현
  src/components/common/input/PasswordInput.tsx
  src/components/my-page/my-info/InfoUpdate.tsx
  src/components/my-page/my-info/InfoUpdateForm.tsx
  src/components/my-page/my-info/PasswordChange.tsx
  src/components/my-page/my-info/PasswordChangeInputField.tsx
  src/hooks/api/auth/useChangePassword.ts
  src/hooks/api/auth/useUpdateUserInfo.ts
  src/hooks/api/index.ts
  src/schemas/form-schema/info-update-schema.ts
  src/schemas/form-schema/password-change-schema.ts
  src/types/api-request-types/auth-request-types.ts
Labels: ✨ Feature, ♻️ Refactor

#262 Fix: 회원가입 page 인증코드 버그 수정 및 UX 개선
  src/components/auth/user-recover-modal/UserRecoverFormModal.tsx
  src/components/my-page/my-info/InfoUpdateForm.tsx
  src/constants/input-variants.ts
  src/hooks/useVerificationCode.ts
  src/index.css
  src/pages/auth/SignUp.tsx
Labels: 🐛 Bug, ♻️ Refactor

#266 Feature: 알림 컴포넌트 헤더에 추가
  src/components/header/nav/NavProfile.tsx
Labels: ✨ Feature

#275 Refactor: 내 정보 조회 msw 적용 & api 연결
  src/components/common/Avatar.tsx
  src/components/header/nav/NavProfile.tsx
  src/hooks/api/auth/useLogin.ts
  src/hooks/api/auth/useTokenRefresh.ts
  src/hooks/api/auth/useUserInformation.ts
  src/mocks/handlers/auth-handler.ts
  src/mocks/handlers/user-info-handler.ts
  src/utils/formatted-phone.ts
  src/utils/map-user-info.ts
Labels: ♻️ Refactor

#279 Refactor: App.tsx에 MainRoutes 연결
  src/App.tsx
  src/pages/TestHub.tsx
  src/routes/MainRoutes.tsx
  src/routes/TestRoutes.tsx
  src/utils/index.ts
  src/utils/registry-test-pages.ts
Labels: ♻️ Refactor

#278 Fix: 로그아웃 시 랜딩페이지로 이동
  src/components/header/nav/NavProfile.tsx
  src/hooks/api/auth/useKakaoCallback.ts
  src/hooks/api/auth/useLogin.ts
  src/hooks/api/auth/useLogout.ts
  src/hooks/api/auth/useTokenRefresh.ts
  src/hooks/api/auth/useUserInformation.ts
Labels: 🐛 Bug

#295 Fix: 탈퇴 회원 버그 수정
  src/pages/auth/Login.tsx
Labels: 🐛 Bug

#299 Refactor: lazy loading 적용
  src/pages/auth/FindEmail.tsx
  src/pages/auth/FindPassword.tsx
  src/pages/index.tsx
  src/pages/my-page/AppliedRecruitment.tsx
  src/pages/my-page/CompletedStudy.tsx
  src/pages/my-page/MyInfo.tsx
  src/routes/MainRoutes.tsx
Labels: ♻️ Refactor
